# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
two_d= np.array([[1,2,3],[4,5,6]]);

# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1,2,3])

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[1,2,3],[4,5,6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d.shape, one_d.size, one_d.dtype, one_d.ndim

((3,), 3, dtype('int32'), 1)

In [5]:
# Attributes of 2-dimensional array
two_d.shape, two_d.size, two_d.dtype, two_d.ndim

((2, 3), 6, dtype('int32'), 2)

In [6]:
# Attributes of 3-dimensional array
three_d.shape , three_d.size, three_d.dtype, three_d.ndim

((1, 2, 3), 6, dtype('int32'), 3)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data_frame= pd.DataFrame(two_d)
data_frame

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones_array= np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array=np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.uniform(0,10,size=(7,2))
random_array

array([[7.11648932, 7.65227729],
       [9.97602288, 8.34146916],
       [0.45857571, 7.42323261],
       [6.23840749, 4.377336  ],
       [2.78962864, 2.21792781],
       [2.92135946, 6.71762988],
       [6.7222924 , 6.16257828]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_random_array=np.random.randn(3,5)
float_random_array.shape
random_float_array = np.random.rand(3, 5)
random_float_array

array([[0.86993307, 0.02263877, 0.61200469, 0.61660326, 0.03901261],
       [0.51262522, 0.3480272 , 0.97059582, 0.16651968, 0.93546203],
       [0.00125979, 0.46607627, 0.39907564, 0.03534475, 0.84911039]])

In [13]:
# Set the random seed to 42
np.random.seed(42);

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_1= np.random.uniform(0,10,size=(4,6))
random_array_1

array([[3.74540119, 9.50714306, 7.31993942, 5.98658484, 1.5601864 ,
        1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012, 7.08072578, 0.20584494,
        9.69909852],
       [8.32442641, 2.12339111, 1.81824967, 1.8340451 , 3.04242243,
        5.24756432],
       [4.31945019, 2.9122914 , 6.11852895, 1.39493861, 2.92144649,
        3.66361843]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_2=np.random.uniform(1,10,size=(3,7));
random_array_2

# Find the unique numbers in the array you just created
np.unique(random_array_2)

array([1.30949669, 1.41805371, 1.58546434, 1.87904903, 2.09834411,
       2.53471711, 2.79706404, 3.32901983, 3.74152392, 4.96137244,
       5.10462986, 5.45659219, 5.62810995, 6.33173112, 6.46790367,
       7.15809724, 8.06658365, 8.27557613, 9.18388362, 9.53996984,
       9.6906883 ])

In [15]:
# Find the 0'th index of the latest array you created
random_array_2[0]

array([5.10462986, 8.06658365, 2.79706404, 5.62810995, 6.33173112,
       1.41805371, 6.46790367])

In [16]:
# Get the first 2 rows of latest array you created
random_array_2[:2]

array([[5.10462986, 8.06658365, 2.79706404, 5.62810995, 6.33173112,
        1.41805371, 6.46790367],
       [2.53471711, 1.58546434, 9.53996984, 9.6906883 , 8.27557613,
        3.74152392, 1.87904903]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_2[:2,:2]

array([[5.10462986, 8.06658365],
       [2.53471711, 1.58546434]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_3=np.random.uniform(0,10,size=(3,5));
ones_array_1=np.ones((3,5))

In [19]:
# Add the two arrays together
random_array_3+ones_array_1

array([[ 7.62522284,  4.11711076,  6.20068021,  6.46710279,  2.84854456],
       [10.69584628,  8.75132823, 10.39498942,  9.9482735 ,  6.97899979],
       [10.21874235,  1.88492502,  2.95982862,  1.45227289,  4.25330331]])

In [20]:
# Create another array of ones of shape (5, 3)
ones_array_2=np.ones((5,3))

In [21]:
# Try add the array of ones and the other most recent array together
ones_array_1+ones_array_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
ones_array_3=np.ones((3,5))
ones_array_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Subtract the new array of ones from the other most recent array
random_array_3-ones_array_3

array([[ 5.62522284,  2.11711076,  4.20068021,  4.46710279,  0.84854456],
       [ 8.69584628,  6.75132823,  8.39498942,  7.9482735 ,  4.97899979],
       [ 8.21874235, -0.11507498,  0.95982862, -0.54772711,  2.25330331]])

In [24]:
# Multiply the ones array with the latest array
np.multiply(random_array_3,ones_array_3)

array([[6.62522284, 3.11711076, 5.20068021, 5.46710279, 1.84854456],
       [9.69584628, 7.75132823, 9.39498942, 8.9482735 , 5.97899979],
       [9.21874235, 0.88492502, 1.95982862, 0.45227289, 3.25330331]])

In [ ]:
# Take the latest array to the power of 2 using '**'
random_array_3**2

In [ ]:
# Do the same thing with np.square()
np.square(random_array_3)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_3)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(random_array_3)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(random_array_3)

In [ ]:
# Find the standard deviation of the latest array
np.std(random_array_3)

In [ ]:
# Find the variance of the latest array
np.var(random_array_3)

In [ ]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array_3,(3,5,1))

In [ ]:
# Transpose the latest array
random_array_3.T

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
int_array_0=np.random.randint(0,10,size=(3,3))
int_array_1=np.random.randint(0,10,size=(3,2))

In [ ]:
# Perform a dot product on the two newest arrays you created
int_array_0*int_array_1

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
int_array_2=np.random.randint(0,10,size=(4,3))
int_array_3=np.random.randint(0,10,size=(4,3))

In [ ]:
# Perform a dot product on the two newest arrays you created
int_array_2*int_array_3

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(int_array_2,int_array_3)


In [ ]:
np.dot(int_array_2.T,int_array_3)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [25]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
compare_array_1=np.random.randint(0,10,size=(2,4))
compare_array_2=np.random.randint(0,10,size=(2,4))

In [26]:
# Compare the two arrays with '>'
compare_array_1>compare_array_2

array([[False, False, False,  True],
       [ True,  True, False,  True]])

What happens when you compare the arrays with `>`?

In [27]:
# Compare the two arrays with '>='
compare_array_1>=compare_array_2

array([[False, False,  True,  True],
       [ True,  True, False,  True]])

In [28]:
# Find which elements of the first array are greater than 7
compare_array_1>7

array([[False, False, False,  True],
       [ True,  True, False,  True]])

In [29]:
# Which parts of each array are equal? (try using '==')
compare_array_1==compare_array_2

array([[False, False,  True, False],
       [False, False, False, False]])

In [30]:
# Sort one of the arrays you just created in ascending order
np.sort(compare_array_1)

array([[1, 4, 7, 9],
       [0, 8, 8, 8]])

In [31]:
# Sort the indexes of one of the arrays you just created
np.argsort(compare_array_1)

array([[0, 1, 2, 3],
       [2, 0, 1, 3]], dtype=int64)

In [32]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(compare_array_1)

3

In [33]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(compare_array_1)

6

In [34]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(compare_array_1,axis=1)

array([3, 0], dtype=int64)

In [35]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(compare_array_1,axis=0)

array([1, 1, 0, 0], dtype=int64)

In [37]:
# Create an array of normally distributed random numbers
normal_dis_array=np.random.randn(3,4)
normal_dis_array

array([[-1.57415529,  0.63795294, -2.04442302,  1.06948089],
       [-0.93376284,  0.78420819, -0.61487576,  0.33289244],
       [-1.38071702, -0.28080629, -0.05981726,  0.96117377]])

In [38]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.